/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    rooms: Room;
    services: Service;
    facilities: Facility;
    gallery: Gallery;
    promotions: Promotion;
    blog: Blog;
    testimonials: Testimonial;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'about-page': AboutPage;
    'rooms-page': RoomsPage;
    'services-page': ServicesPage;
    'contact-page': ContactPage;
    'reservation-page': ReservationPage;
    'blog-page': BlogPage;
    'legal-pages': LegalPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'rooms-page': RoomsPageSelect<false> | RoomsPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'reservation-page': ReservationPageSelect<false> | ReservationPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  category: 'general' | 'hero' | 'room' | 'facility' | 'gallery' | 'promotion' | 'logo';
  uploadedBy?: (number | null) | User;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  title: string;
  slug: string;
  category?: string | null;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: number | Media;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        alt: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  inclusions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  standards?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  experiences?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  capacity?: number | null;
  capacityLabel?: string | null;
  bedType?: string | null;
  roomSize?: string | null;
  view?: string | null;
  startingPrice?: number | null;
  currency?: string | null;
  rateNote?: string | null;
  reviewsLabel?: string | null;
  availabilityLabel?: string | null;
  depositLabel?: string | null;
  passengerLabel?: string | null;
  bestFor?: string | null;
  bookingURL?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  eyebrow?: string | null;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: number | Media;
  detailImage?: (number | null) | Media;
  cta?: {
    label?: string | null;
    url?: string | null;
    openInNewTab?: boolean | null;
    variant?: ('primary' | 'secondary' | 'text') | null;
  };
  duration?: string | null;
  location?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  rituals?:
    | {
        title: string;
        category?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        duration?: string | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        alt: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        alt: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  image: number | Media;
  alt: string;
  caption?: string | null;
  category: 'resort' | 'room' | 'facility' | 'restaurant' | 'experience' | 'surrounding';
  featured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  desktopImage: number | Media;
  mobileImage?: (number | null) | Media;
  ctaLabel?: string | null;
  ctaURL?: string | null;
  promoCode?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  category: string;
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: number | Media;
  readTime?: string | null;
  articleDate?: string | null;
  featured?: boolean | null;
  curatorChoice?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  guestName: string;
  guestLocation?: string | null;
  rating: number;
  review: string;
  source?: string | null;
  sourceURL?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  uploadedBy?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  description?: T;
  featuredImage?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  inclusions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        label?: T;
        id?: T;
      };
  experiences?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  capacity?: T;
  capacityLabel?: T;
  bedType?: T;
  roomSize?: T;
  view?: T;
  startingPrice?: T;
  currency?: T;
  rateNote?: T;
  reviewsLabel?: T;
  availabilityLabel?: T;
  depositLabel?: T;
  passengerLabel?: T;
  bestFor?: T;
  bookingURL?: T;
  featured?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  summary?: T;
  description?: T;
  featuredImage?: T;
  detailImage?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        variant?: T;
      };
  duration?: T;
  location?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  rituals?:
    | T
    | {
        title?: T;
        category?: T;
        description?: T;
        image?: T;
        duration?: T;
        featured?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  featured?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  featured?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  alt?: T;
  caption?: T;
  category?: T;
  featured?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  desktopImage?: T;
  mobileImage?: T;
  ctaLabel?: T;
  ctaURL?: T;
  promoCode?: T;
  startDate?: T;
  endDate?: T;
  featured?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  readTime?: T;
  articleDate?: T;
  featured?: T;
  curatorChoice?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  guestName?: T;
  guestLocation?: T;
  rating?: T;
  review?: T;
  source?: T;
  sourceURL?: T;
  featured?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  shortDescription?: string | null;
  logoDark?: (number | null) | Media;
  logoLight?: (number | null) | Media;
  favicon?: (number | null) | Media;
  defaultSEOTitle?: string | null;
  defaultSEODescription?: string | null;
  defaultOpenGraphImage?: (number | null) | Media;
  contactEmail?: string | null;
  phone?: string | null;
  whatsAppNumber?: string | null;
  address?: string | null;
  googleMapsURL?: string | null;
  instagramURL?: string | null;
  facebookURL?: string | null;
  youTubeURL?: string | null;
  bookingURL?: string | null;
  defaultLocale?: string | null;
  timezone?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navigationItems?:
    | {
        label: string;
        pageURL:
          | '/'
          | '/about'
          | '/about-us'
          | '/villa'
          | '/rooms'
          | '/reservation'
          | '/facilities'
          | '/services'
          | '/gallery'
          | '/blog'
          | '/promotions'
          | '/contact';
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  primaryCTA: {
    label: string;
    url: string;
    openInNewTab?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brand?: {
    logo?: (number | null) | Media;
    description?: string | null;
    tagline?: string | null;
  };
  shortDescription?: string | null;
  contact?: {
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    address?: string | null;
  };
  contactInformation?: {
    phone?: string | null;
    email?: string | null;
    whatsApp?: string | null;
    address?: string | null;
  };
  navigationColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('instagram' | 'facebook' | 'youtube' | 'whatsapp' | 'email' | 'other') | null;
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  quickLinks?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  bookingCta?: {
    label?: string | null;
    url?: string | null;
    openInNewTab?: boolean | null;
    variant?: ('primary' | 'secondary' | 'text') | null;
  };
  copyrightText?: string | null;
  termsURL?: string | null;
  privacyURL?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading: string;
    description?: string | null;
    backgroundImage: number | Media;
    primaryCTA?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      variant?: ('primary' | 'secondary' | 'text') | null;
    };
    secondaryCTA?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      variant?: ('primary' | 'secondary' | 'text') | null;
    };
    overlayIntensity?: number | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  bookingPreview?: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    sectionAriaLabel?: string | null;
    formAriaLabel?: string | null;
    checkInLabel?: string | null;
    checkOutLabel?: string | null;
    guestsLabel?: string | null;
    promotionLinkLabel?: string | null;
    promotionLinkURL?: string | null;
    submitButtonLabel?: string | null;
    submitButtonURL?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  introduction?: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  signatureExperiences?: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    selectedServices?: (number | Service)[] | null;
    button?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      variant?: ('primary' | 'secondary' | 'text') | null;
    };
    active?: boolean | null;
    sortOrder?: number | null;
  };
  typeOfRooms?: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    selectedRooms?: (number | Room)[] | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  /**
   * Placeholder note only. This frontend section will use Google Reviews or another review platform later.
   */
  testimonialNote?: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    /**
     * This keeps the Home CMS section order aligned with frontend while avoiding a temporary manual testimonial source.
     */
    note?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  journalPreview?: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    selectedArticles?: (number | Blog)[] | null;
    button?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      variant?: ('primary' | 'secondary' | 'text') | null;
    };
    active?: boolean | null;
    sortOrder?: number | null;
  };
  contactPreview?: {
    /**
     * Editable label for staff/admin only. Use this to match the visible frontend section purpose without changing code structure.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    locationHeading?: string | null;
    address?: string | null;
    emailLabel?: string | null;
    email?: string | null;
    phoneLabel?: string | null;
    phone?: string | null;
    mapEmbedURL?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading: string;
    description?: string | null;
    image?: (number | null) | Media;
    scrollCueLabel?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  story?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  principles?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  team?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading?: string | null;
    quote?: string | null;
    members?:
      | {
          name: string;
          role?: string | null;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  finalCTA?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading?: string | null;
    image?: (number | null) | Media;
    button?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      variant?: ('primary' | 'secondary' | 'text') | null;
    };
    active?: boolean | null;
    sortOrder?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms-page".
 */
export interface RoomsPage {
  id: number;
  hero: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading: string;
    description?: string | null;
    image?: (number | null) | Media;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  availabilityBar?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    sectionAriaLabel?: string | null;
    formAriaLabel?: string | null;
    checkInLabel?: string | null;
    checkOutLabel?: string | null;
    guestsLabel?: string | null;
    promotionLinkLabel?: string | null;
    promotionLinkURL?: string | null;
    submitButtonLabel?: string | null;
    submitButtonURL?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  roomCollection?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    ratingSymbol?: string | null;
    startFromLabel?: string | null;
    nightSuffixLabel?: string | null;
    statusLabel?: string | null;
    depositLabel?: string | null;
    bedsLabel?: string | null;
    passengerLabel?: string | null;
    detailButtonLabel?: string | null;
    button?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      variant?: ('primary' | 'secondary' | 'text') | null;
    };
    active?: boolean | null;
    sortOrder?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading: string;
    description?: string | null;
    image?: (number | null) | Media;
    scrollCueLabel?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  intro?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  signatureServices?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    ariaLabel?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  tailoredMoment?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    metaLabelOne?: string | null;
    metaLabelTwo?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  finalCTA?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading?: string | null;
    description?: string | null;
    primary?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    secondary?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    active?: boolean | null;
    sortOrder?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading: string;
    description?: string | null;
    image?: (number | null) | Media;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  contactInquiry?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading?: string | null;
    description?: string | null;
    locationLabel?: string | null;
    locationText?: string | null;
    whatsAppLabel?: string | null;
    whatsAppText?: string | null;
    emailLabel?: string | null;
    emailText?: string | null;
    conciergeAriaLabel?: string | null;
    conciergeHeading?: string | null;
    button?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    phone?: string | null;
    email?: string | null;
    whatsApp?: string | null;
    address?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  contactForm?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    ariaLabel?: string | null;
    heading?: string | null;
    description?: string | null;
    nameLabel?: string | null;
    namePlaceholder?: string | null;
    emailLabel?: string | null;
    emailPlaceholder?: string | null;
    subjectLabel?: string | null;
    subjectOptionOne?: string | null;
    subjectOptionTwo?: string | null;
    subjectOptionThree?: string | null;
    subjectOptionFour?: string | null;
    messageLabel?: string | null;
    messagePlaceholder?: string | null;
    submitButtonLabel?: string | null;
    submittingButtonLabel?: string | null;
    whatsAppMessageIntro?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  mapSection?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    heading?: string | null;
    description?: string | null;
    locationHeading?: string | null;
    mapTitle?: string | null;
    mapEmbedURL?: string | null;
    button?: {
      label?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
    };
    active?: boolean | null;
    sortOrder?: number | null;
  };
  quote?: {
    /**
     * Editable admin label. Keep this aligned with the actual frontend section purpose.
     */
    sectionName?: string | null;
    ariaLabel?: string | null;
    text?: string | null;
    active?: boolean | null;
    sortOrder?: number | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservation-page".
 */
export interface ReservationPage {
  id: number;
  heroEyebrow?: string | null;
  heroHeading: string;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  searchPreview?:
    | {
        label: string;
        value: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  bookingBenefits?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  roomDetails?:
    | {
        room: number | Room;
        reviews?: string | null;
        availabilityLabel?: string | null;
        deposit?: string | null;
        beds?: string | null;
        passenger?: string | null;
        breakfast?: string | null;
        selected?: boolean | null;
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  overview?: {
    arrival?: string | null;
    departure?: string | null;
    items?:
      | {
          room?: (number | null) | Room;
          roomCount?: string | null;
          passenger?: string | null;
          subtotal?: string | null;
          id?: string | null;
        }[]
      | null;
    total?: string | null;
  };
  whatsAppCTA?: {
    label?: string | null;
    url?: string | null;
    openInNewTab?: boolean | null;
    variant?: ('primary' | 'secondary' | 'text') | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  heroEyebrow?: string | null;
  heroHeading: string;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  introHeading?: string | null;
  introDescription?: string | null;
  listingHeading?: string | null;
  listingDescription?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    canonicalURL?: string | null;
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  terms: {
    eyebrow?: string | null;
    title: string;
    summary?: string | null;
    updatedAtLabel?: string | null;
    updatedAt?: string | null;
    sections?:
      | {
          title: string;
          body?:
            | {
                paragraph: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    seo?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
      openGraphImage?: (number | null) | Media;
      canonicalURL?: string | null;
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
  };
  privacy: {
    eyebrow?: string | null;
    title: string;
    summary?: string | null;
    updatedAtLabel?: string | null;
    updatedAt?: string | null;
    sections?:
      | {
          title: string;
          body?:
            | {
                paragraph: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    seo?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
      openGraphImage?: (number | null) | Media;
      canonicalURL?: string | null;
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
  };
  cookies: {
    eyebrow?: string | null;
    title: string;
    summary?: string | null;
    updatedAtLabel?: string | null;
    updatedAt?: string | null;
    sections?:
      | {
          title: string;
          body?:
            | {
                paragraph: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    seo?: {
      metaTitle?: string | null;
      metaDescription?: string | null;
      openGraphImage?: (number | null) | Media;
      canonicalURL?: string | null;
      noIndex?: boolean | null;
      noFollow?: boolean | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortDescription?: T;
  logoDark?: T;
  logoLight?: T;
  favicon?: T;
  defaultSEOTitle?: T;
  defaultSEODescription?: T;
  defaultOpenGraphImage?: T;
  contactEmail?: T;
  phone?: T;
  whatsAppNumber?: T;
  address?: T;
  googleMapsURL?: T;
  instagramURL?: T;
  facebookURL?: T;
  youTubeURL?: T;
  bookingURL?: T;
  defaultLocale?: T;
  timezone?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigationItems?:
    | T
    | {
        label?: T;
        pageURL?: T;
        active?: T;
        id?: T;
      };
  primaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        logo?: T;
        description?: T;
        tagline?: T;
      };
  shortDescription?: T;
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
        address?: T;
      };
  contactInformation?:
    | T
    | {
        phone?: T;
        email?: T;
        whatsApp?: T;
        address?: T;
      };
  navigationColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  quickLinks?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  bookingCta?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        variant?: T;
      };
  copyrightText?: T;
  termsURL?: T;
  privacyURL?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        backgroundImage?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              variant?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              variant?: T;
            };
        overlayIntensity?: T;
        active?: T;
        sortOrder?: T;
      };
  bookingPreview?:
    | T
    | {
        sectionName?: T;
        sectionAriaLabel?: T;
        formAriaLabel?: T;
        checkInLabel?: T;
        checkOutLabel?: T;
        guestsLabel?: T;
        promotionLinkLabel?: T;
        promotionLinkURL?: T;
        submitButtonLabel?: T;
        submitButtonURL?: T;
        active?: T;
        sortOrder?: T;
      };
  introduction?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        image?: T;
        active?: T;
        sortOrder?: T;
      };
  signatureExperiences?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        selectedServices?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              variant?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  typeOfRooms?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        selectedRooms?: T;
        active?: T;
        sortOrder?: T;
      };
  testimonialNote?:
    | T
    | {
        sectionName?: T;
        note?: T;
        active?: T;
        sortOrder?: T;
      };
  journalPreview?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        selectedArticles?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              variant?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  contactPreview?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        locationHeading?: T;
        address?: T;
        emailLabel?: T;
        email?: T;
        phoneLabel?: T;
        phone?: T;
        mapEmbedURL?: T;
        active?: T;
        sortOrder?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        image?: T;
        scrollCueLabel?: T;
        active?: T;
        sortOrder?: T;
      };
  story?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        active?: T;
        sortOrder?: T;
      };
  principles?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  team?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        quote?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  finalCTA?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        image?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              variant?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms-page_select".
 */
export interface RoomsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        description?: T;
        image?: T;
        active?: T;
        sortOrder?: T;
      };
  availabilityBar?:
    | T
    | {
        sectionName?: T;
        sectionAriaLabel?: T;
        formAriaLabel?: T;
        checkInLabel?: T;
        checkOutLabel?: T;
        guestsLabel?: T;
        promotionLinkLabel?: T;
        promotionLinkURL?: T;
        submitButtonLabel?: T;
        submitButtonURL?: T;
        active?: T;
        sortOrder?: T;
      };
  roomCollection?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        ratingSymbol?: T;
        startFromLabel?: T;
        nightSuffixLabel?: T;
        statusLabel?: T;
        depositLabel?: T;
        bedsLabel?: T;
        passengerLabel?: T;
        detailButtonLabel?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              variant?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        description?: T;
        image?: T;
        scrollCueLabel?: T;
        active?: T;
        sortOrder?: T;
      };
  intro?:
    | T
    | {
        sectionName?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        active?: T;
        sortOrder?: T;
      };
  signatureServices?:
    | T
    | {
        sectionName?: T;
        ariaLabel?: T;
        active?: T;
        sortOrder?: T;
      };
  tailoredMoment?:
    | T
    | {
        sectionName?: T;
        metaLabelOne?: T;
        metaLabelTwo?: T;
        active?: T;
        sortOrder?: T;
      };
  finalCTA?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        description?: T;
        primary?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        description?: T;
        image?: T;
        active?: T;
        sortOrder?: T;
      };
  contactInquiry?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        description?: T;
        locationLabel?: T;
        locationText?: T;
        whatsAppLabel?: T;
        whatsAppText?: T;
        emailLabel?: T;
        emailText?: T;
        conciergeAriaLabel?: T;
        conciergeHeading?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        phone?: T;
        email?: T;
        whatsApp?: T;
        address?: T;
        active?: T;
        sortOrder?: T;
      };
  contactForm?:
    | T
    | {
        sectionName?: T;
        ariaLabel?: T;
        heading?: T;
        description?: T;
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        subjectLabel?: T;
        subjectOptionOne?: T;
        subjectOptionTwo?: T;
        subjectOptionThree?: T;
        subjectOptionFour?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitButtonLabel?: T;
        submittingButtonLabel?: T;
        whatsAppMessageIntro?: T;
        active?: T;
        sortOrder?: T;
      };
  mapSection?:
    | T
    | {
        sectionName?: T;
        heading?: T;
        description?: T;
        locationHeading?: T;
        mapTitle?: T;
        mapEmbedURL?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
            };
        active?: T;
        sortOrder?: T;
      };
  quote?:
    | T
    | {
        sectionName?: T;
        ariaLabel?: T;
        text?: T;
        active?: T;
        sortOrder?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservation-page_select".
 */
export interface ReservationPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroDescription?: T;
  heroImage?: T;
  searchPreview?:
    | T
    | {
        label?: T;
        value?: T;
        detail?: T;
        id?: T;
      };
  bookingBenefits?:
    | T
    | {
        label?: T;
        id?: T;
      };
  roomDetails?:
    | T
    | {
        room?: T;
        reviews?: T;
        availabilityLabel?: T;
        deposit?: T;
        beds?: T;
        passenger?: T;
        breakfast?: T;
        selected?: T;
        badge?: T;
        id?: T;
      };
  overview?:
    | T
    | {
        arrival?: T;
        departure?: T;
        items?:
          | T
          | {
              room?: T;
              roomCount?: T;
              passenger?: T;
              subtotal?: T;
              id?: T;
            };
        total?: T;
      };
  whatsAppCTA?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        variant?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroDescription?: T;
  heroImage?: T;
  introHeading?: T;
  introDescription?: T;
  listingHeading?: T;
  listingDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
        canonicalURL?: T;
        noIndex?: T;
        noFollow?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  terms?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        summary?: T;
        updatedAtLabel?: T;
        updatedAt?: T;
        sections?:
          | T
          | {
              title?: T;
              body?:
                | T
                | {
                    paragraph?: T;
                    id?: T;
                  };
              id?: T;
            };
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              openGraphImage?: T;
              canonicalURL?: T;
              noIndex?: T;
              noFollow?: T;
            };
      };
  privacy?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        summary?: T;
        updatedAtLabel?: T;
        updatedAt?: T;
        sections?:
          | T
          | {
              title?: T;
              body?:
                | T
                | {
                    paragraph?: T;
                    id?: T;
                  };
              id?: T;
            };
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              openGraphImage?: T;
              canonicalURL?: T;
              noIndex?: T;
              noFollow?: T;
            };
      };
  cookies?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        summary?: T;
        updatedAtLabel?: T;
        updatedAt?: T;
        sections?:
          | T
          | {
              title?: T;
              body?:
                | T
                | {
                    paragraph?: T;
                    id?: T;
                  };
              id?: T;
            };
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              openGraphImage?: T;
              canonicalURL?: T;
              noIndex?: T;
              noFollow?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}